_allow_dotted_keys:
    value: false
_convert_dict:
    value: true
_fields:
    value:
        batch_size: 256
        device: cuda
        model: |
            activation: &id001 !!python/tuple
            - true
            - true
            - true
            bias: false
            dropout: 0.1
            emb_dim: 64
            ff_dim: 256
            flash: true
            layer_norm: true
            mask: true
            mlp: *id001
            mlp_bias: true
            num_heads: !!python/tuple
            - 1
            - 1
            - 1
            num_layers: 3
            pos_enc: rotary
            pos_max_len: 256
        task: |
            max_variables: 12
        test_size: 8192
        training: |
            eval_iter: 100
            freeze_out: false
            freeze_value: false
            get_attn: 1000
            get_checkpoints: 500
            identity_query: false
            label_smoothing: 0.05
            lr: 0.0006
            optimizer: adamw
            schedule: triangle
            total_steps: 60000
            warmup_steps: 20000
            weight_decay: 0.01
        vocab_size: 16
        wandb: |
            project: Reasoning
        work_dir: results
_locked:
    value: false
_sort_keys:
    value: true
_type_safe:
    value: true
_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
